/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	int amount;
};
typedef struct inputs inputs;

#define WITHDRAW_PROG 0x23451111
#define WITHDRAW_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define READ 1
extern  int * read_1(inputs *, CLIENT *);
extern  int * read_1_svc(inputs *, struct svc_req *);
extern int withdraw_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READ 1
extern  int * read_1();
extern  int * read_1_svc();
extern int withdraw_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK_H_RPCGEN */
