/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"

int *
read_1_svc(inputs *argp, struct svc_req *rqstp)
{
	static int  result;
	int balance;

	printf("i got requset\n");

	FILE *fp;
   	char str[60];

   	/* opening file for reading */
   	fp = fopen("file.txt" , "r");

   	if(fp == NULL) 
   	{
      		perror("Error opening file");
      		//return(-1);
   	}

   	if( fgets (str, 60, fp)!=NULL ) 
   	{
      		/* writing content to stdout */
      		balance = atoi(strtok(str,"\n"));
		result = balance - argp->amount;
		fprintf(fp,"%d",result);
		
   	}

   	fclose(fp);

	return &result;
}
