/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank.h"

bool_t
xdr_inputs (XDR *xdrs, inputs *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->amount))
		 return FALSE;
	return TRUE;
}
